### ISSUE TITLE
Create Vendor Link List with Vendor name as a collection

### ISSUE THREAD

**Issue by freakdesign** [freakdesign/shopifyFD#16]
This is an enhancement request pulled from the feature request form. 

The idea being that a function is created that will create a linklist of all the vendors. When there is a collection title that matches the vendor name link to that instead of the vendor link.

**Comment by rickydazla** [comment]
_So many_ Vendors!

**Comment by freakdesign** [comment]
You know it! 
I'm not sure how much worth this enhancement would have - thoughts?. Would be curious to know if you (or others) have had some need for it. Since we can build the same functionality into the theme using the existing vendor linklist I wonder if this is overkill.

**Comment by rickydazla** [comment]
I can see some use for it after the fact. I've never really wanted for it because I maintain very few multi-vendor stores and those that have and needed one created the list as they were going along. A couple of stores have an automagically generated nav list and a couple use a curated list of _featured vendors_. I guess it could be useful for others to create and then possibly cherry-pick from...

**Comment by freakdesign** [comment]
The need for this is very low so it's (finally) time to wave goodbye to this enhancement for now. We can revive it should that change.
