### ISSUE TITLE
Unexpected Collection table HTML

### ISSUE THREAD

**Issue by ctopjian** [freakdesign/shopifyFD#22]
Jason,

I noticed there are a ton of changes coming to the "product setup page". I suspect this to be the cause of the recent error?  I was looking at your recent commits and it looks like you were possible trying to fix this already. On my clone of your rep I see *line 2852 var tpc = $('ul.product-collections-list');* causing the error.

That element is not found on the HTML of the product page any longer. If I can help I am happy to, this is the first time I have actually cracked open your code. Thought I would try to fix it and submit a pull-request.  I am not understanding why it would break the load of ShopifyFD due to this notice though. 

Thanks! See screen shot attached.

![recent-error](https://cloud.githubusercontent.com/assets/1432601/6639177/5e652980-c95b-11e4-8bf3-7f7ed72aab7e.png)

**Comment by freakdesign** [comment]
Since the majority of Shopify stores are now on the new layout the ShopifyFD base code has been updated to support the new layout. What you've shown here is the old layout. Don't waste your time doing a pull request because you'll likely have the new layout by days end.

For reference, the new layout looks like this:
![2015-03-13 23 44 42](https://cloud.githubusercontent.com/assets/1378665/6639402/04f60f92-c9db-11e4-96e2-aa36e573edb6.png)

If you need access to the old version I can point you in the right direction, or you can just build a bookmarklet from earlier commits.

**Comment by ctopjian** [comment]
Jason - ok thanks for the update! Not a big deal, hoping they update my stores today! :-)
Thanks again for the great utility!!!

**Comment by freakdesign** [comment]
A few others have emailed me about so I might as well just make a Legacy bookmarklet to keep everyone trucking along. Here ya go ;)

https://freakdesign-us.s3.amazonaws.com/shopify/shopifyFD/legacy/installation.html

Let me know if that works for you.

**Comment by ctopjian** [comment]
Awesome will give it a try...  Thanks a ton

**Comment by freakdesign** [comment]
Users have reported that the legacy version is aok. May not even be needed now but it should be safe to assume that this issue is sorted.
