### ISSUE TITLE
Search and View SKUs + IDs

### ISSUE THREAD

**Issue by MicrobrewMedia** [freakdesign/shopifyFD#53]
After loading ShopifyFD then running a search Clicking Show SKUs and ID, then running another search button is not clickable and shows "Data Loaded" but this is referring to the last search not the current.

**Comment by freakdesign** [comment]
Thanks for issue report - I can confirm this one too. 👍

The current code uses the url to help know what page the user is on, but intentionally ignores any hashes or querystrings. Since a search appends a querystring, the code does not recognise this as a _new_ page so won't (re)fire the functions.

The groundwork has been started to better handle querystrings in urls so once that's done this issue should be resolved as a side effect. That update would also let some features run on paginated views.

**Comment by freakdesign** [comment]
Whilst this isn't v2, a patch has been applied in https://github.com/freakdesign/shopifyFD/commit/8e8135ef602f487d85b3e4d56509e13658181a99
