### ISSUE TITLE
Meta fields not loading into the edit screens

### ISSUE THREAD

**Issue by lmartins** [freakdesign/shopifyFD#57]
I using ShopifyFD on my second project and trying to apply the same configuration that worked for me on the first project. 

On the second project though I can't get any metafield to show up on the Custom Fields box, even though they show-up on the MetaFields edit screen, as can be seen on this screenshot:

![screenshot 2016-06-13 17 03 05](https://cloud.githubusercontent.com/assets/151981/16014380/d5e5db4e-3188-11e6-9815-60cd0fbff27f.png)

Is there anything else I can try to fix this?

**Comment by freakdesign** [comment]
Looks like you're using a custom namespace, rather than the default `c_f`. Did you set this up correctly?
Check the (old) [help PDF](https://freakdesign-us.s3.amazonaws.com/shopify/custom_fields/freakdesign-custom-fields-for-shopify-guide.pdf) and this quick blog post on [setting up custom fields](http://freakdesign.com.au/blogs/news/179809927-how-to-setup-the-custom-fields-for-shopify-chrome-extension).

**Comment by lmartins** [comment]
Thanks Jason. The weird thing is that those custom namespaces do work on my other project:
<img width="1075" alt="screenshot 2016-06-14 07 09 00" src="https://cloud.githubusercontent.com/assets/151981/16032629/f2745f08-31fe-11e6-90f5-424753f149d8.png">

This render as:

<img width="811" alt="screenshot 2016-06-14 07 10 13" src="https://cloud.githubusercontent.com/assets/151981/16032641/15fc198e-31ff-11e6-80e8-c013859ac570.png">

On this new site, once I changed the name space as you suggest it started working.

Any ideia why it worked before?

**Comment by freakdesign** [comment]
I would assume that the custom namespace was set up in the other store in the `custom_fields_config.whitelist metafield`. Check the value of that metafield in the store where it works.

**Comment by lmartins** [comment]
That was it, thanks again Jason.
